version: '3'
services:
  baby_overflow:
    build: ./task
    container_name: baby_overflow
    restart: always
    ports:
      - 1337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "150M"

