version: '3'
services:
  nullazino777:
    build: ./task
    container_name: nullazino777
    restart: always
    ports:
      - 1337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "150M"

