version: '3'
services:
  goverflow:
    build: ./task
    container_name: goverflow
    restart: always
    ports:
      - 1337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200M"

